[package]
name = "storage"
edition = "2024"
version.workspace = true

[dependencies]
bookshelf_core = { package = "bookshelf-core", path = "../core" }
anyhow.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
